title: Brian Vineyard # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Brian, and I am a data analyst with over 12 years of experience leading projects to improve customer service and lower costs.
  <br><br>
  I have a BS in Management Information Systems at CSU Sacramento, and certifications in <a href="https://www.coursera.org/account/accomplishments/specialization/ASXWYZYZEKFW">IBM Data Science</a>, and <a href="https://www.udemy.com/certificate/UC-379a77ba-b265-4691-ab84-7b006824dd3f/?utm_source=sendgrid.com&utm_medium=email&utm_campaign=email">Microsft Power BI Business Intelligence</a>.
  <br><br>
  <a href="linkedin.com/in/brian-vineyard/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
